# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/website-deployment/blob/main/templates/hugo-deploy.tftpl.toml

# deployment-specific configuration, for all other config see `hugo.toml`
# and https://gohugo.io/hosting-and-deployment/hugo-deploy/

[[deployment.targets]]
  name                     = "preview"
  URL                      = "s3://workloadsio-preview-site-1f1j?region=us-west-2"
  cloudFrontDistributionID = "EZB07WTY6BI7U"

[[deployment.targets]]
  name                     = "live"
  URL                      = "s3://workloadsio-site-1f1j?region=us-west-2"
  cloudFrontDistributionID = "E2ATAM9S3I0AAR"
