  [[deployment.targets]]
    name = "preview"
    # see https://gocloud.dev/howto/blob/#s3
    URL = "s3://workloadsio-site-preview-1f1j?region=us-west-2"
    cloudFrontDistributionID = "<CloudFront Distribution ID>"

  [[deployment.targets]]
    name = "live"
    # see https://gocloud.dev/howto/blob/#s3
    URL = "s3://workloadsio-site-preview-1f1j?region=us-west-2"
    cloudFrontDistributionID = "E2ATAM9S3I0AAR"
