# deployment-specific configuration, for all other config see `hugo.toml`

# see https://gohugo.io/hosting-and-deployment/hugo-deploy/
[deployment]
  [[deployment.targets]]
    name = "local"
    URL  = "file://./public"

  [[deployment.targets]]
    name = "preview"
    # see https://gocloud.dev/howto/blob/#s3
    URL = "s3://workloadsio-site-preview-1f1j?region=us-west-2"
    cloudFrontDistributionID = "<CloudFront Distribution ID>"

  [[deployment.targets]]
    name = "live"
    # see https://gocloud.dev/howto/blob/#s3
    URL = "s3://workloadsio-site-preview-1f1j?region=us-west-2"
    cloudFrontDistributionID = "E2ATAM9S3I0AAR"
